### ISSUE TITLE
autoAddSpace.enable should be false by default

### ISSUE THREAD

**Issue by doggy8088** [Talljack/vscode-auto-space#16]
I think the `autoAddSpace.enable` setting should be `false` by default. It because the default settings might broken some code in the VSCode editor and the user might now know it.

**Comment by doggy8088** [comment]
FYI: https://github.com/microsoft/vscode/issues/145859#issuecomment-1076162885

**Comment by Talljack** [comment]
I don't think `autoAddSpace.enable` of value is default `false`, because when you want to use this Vscode extension that I think you want to auto add space in the editor. If is `false` user need to open it.
Maybe I might be able to highlight this to remind the user.
Welcome to continue the discussion.

**Comment by doggy8088** [comment]
For now, your extension will auto add space to ANY language which some languages might broken by this extension easily. What if you support only specific languages by default such as Markdown, Text file, ... etc. and user can add more supported language by their will.

**Comment by Talljack** [comment]
Perhaps many of them are issues that I think about from my own perspective. These are indeed issues. I think it can be set to automatically add spaces to comments and can be configured to support more languages.

**Comment by Talljack** [comment]
In the latest version of 1.4.0, You can turn on formatOnDocument and turn off formatOnSave
